### PR TITLE
Remove `electron/remote` and properly use React Context

### PR DESCRIPTION
**Pull request by Drylozu**
The title says everything.

### CODE REVIEW

**Comment by Drylozu** [comment]
Maybe wait 2-4 days for ytdl-core 404 fix? This PR is using the forked version.

**Comment by FreeAoi** [comment]
Thx man {3

**Comment by FreeAoi** [comment]
I will merge it and when ytdl-core gets fixed, I update it

**Comment by tofantofan** [comment]
> bc1qjjplftu2yflnn7q53p5sh673gj2qw0a7v3flrp

**Pull request merged**
